### ISSUE TITLE
Usage on Raspberry pi HassOS

### ISSUE THREAD

**Issue by luizbalestreri** [lbschenkel/broadlink-bridge#10]
I Sucefully installed the addon on raspberry pi, but it seems its configured to start on docker as I receive the follwing error:

404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_c523f6d3_broadlink_bridge: Not Found ("No such image: c523f6d3/armv7-addon-broadlink_bridge:0.1.6")

Can I manage to work around on raspberry pi?

**Comment by lbschenkel** [comment]
Never saw this before. What is supposed to happen is that the image should be built on your own machine, and then added as an add-on. Perhaps the build process failed earlier?

**Comment by lbschenkel** [comment]
Closing due to lack of response.
