### ISSUE TITLE
Command repeats doesnt work

### ISSUE THREAD

**Issue by timota** [lbschenkel/broadlink-bridge#11]
Hi, 

looks like command repeats doesnt work for IR, at least i can't debug to provide more info. 

Non of these work

```
❯ curl -X POST -d "5*JgBQAAABJpITNhQ1FBEUNhMSEzYTEhQ1FDYTEhM2FDUUERQSEzYTNhQ1FBEUEhMSExITNhMSEzYUERQ2EzYTNxM2ExITNhMSEwAEzQABJkkTAA0FAAAAAAAA" 192.168.1.XXX:8780/device/rm4
❯ curl -X POST -d "fireplace/power" 192.168.1.XXX:8780/device/rm4
```  

where:
[commands]
fireplace/power = 2*JgBQAAABJpITNhQ1FBEUNhMSEzYTEhQ1FDYTEhM2FDUUERQSEzYTNhQ1FBEUEhMSExITNhMSEzYUERQ2EzYTNxM2ExITNhMSEwAEzQABJkkTAA0FAAAAAAAA

Can you please help with this, at least can tell how to debug

**Comment by timota** [comment]
my fault, code format has to be changed to make it work. Issue can be closed

**Comment by lbschenkel** [comment]
> my fault, code format has to be changed to make it work. Issue can be closed

Sorry, what was the issue again? Was was the "code format"?

**Comment by timota** [comment]
i have used codes from broadlink integration in HA that have been taken with alt mode. Those codes are not ended with `==`,  length are incorrect. I have learned new codes without alt mode and they work as expected.
