### ISSUE TITLE
Link to Node.js Project?

### ISSUE THREAD

**Issue by 401Unauthorized** [lbschenkel/broadlink-bridge#12]
Hi @lbschenkel,

I've realized that we have similar projects that share the same name.

Last year, I created a HTTP to Broadlink service written in Node.js.
You can find it on [GitHub](https://github.com/401Unauthorized/broadlink-bridge) & [NPM](https://www.npmjs.com/package/broadlink-bridge).

To avoid confusion, would you be interested in listing each others project in the README?

For instance, I would add something like "If you are looking for a similar project written in Python, check out broadlink-bridge by lbschenkel." and will include a link to this repo.

Let me know your thoughts,
-- Stephen

**Comment by lbschenkel** [comment]
Sure, I will amend the README. But mine came first! ;-)
