### ISSUE TITLE
Repeat Commands

### ISSUE THREAD

**Issue by undulattice** [lbschenkel/broadlink-bridge#2]
Been using this for a while. It's great!
I'd like to use the repeats option mentioned in the readme and get away from using scripts to do it.

I've got the code learned and tested. But when I add the 2* to the beginning of the string, I get the following error:

```
Client error http://127.0.0.1:8780/device/192.168.2.100.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 120, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

Here's the relevant REST command:

```
new_proj_off:
    url: http://127.0.0.1:8780/device/192.168.2.100
    method: post
    payload: 2*JgBQAAABKZQTEhM3ExIUEhM3EzUVEhQSEzcTEhM3FDcTEhMSEzYVNxMSEzcTOBM1FRITNxQSExITNxMSFBEUEhM3ExITNxQ3EwAFCAABKUoTAA0FAAAAAAAAAAA=
```

Have also tried it with spaces and get the same result.

Any help greatly appreciated. :-)

**Comment by lbschenkel** [comment]
Thank you for the report. I'll look into it.

**Comment by lbschenkel** [comment]
It was a bug: it should be fixed in version 0.1.4 of the bridge and add-on. Please update to it and let me know how it goes. Thanks again for the reporting this.

**Comment by lbschenkel** [comment]
Given the lack of follow-up I'm going to go ahead and close this issue. If you still encounter the same problem after updating, please reopen it.

**Comment by dmartella** [comment]
Hi 
The update solved the issue
Thanks

Inviato da iPhone

**Comment by undulattice** [comment]
Sorry, I missed this coming in.
Apologies for the delay.

Problem solved. Great work. Thank you. :-)
