### ISSUE TITLE
Missing package in Docker build: py3-pip

### ISSUE THREAD

**Issue by mmakaay** [lbschenkel/broadlink-bridge#6]
Thanks for your effort. It looks a lot like the thing that I was about to build myself. Glad to see somebody got the same itch before me ;-) I'm going to try out the code on my system.

I tried building the Docker image, but it tripped over pip3 not being available in the image.
The easy fix was to add the package for it to the build:

```Dockerfile
RUN apk add py3-pip py3-cryptography py3-paho-mqtt
```

**Comment by lbschenkel** [comment]
Thanks. Fixed.
