### ISSUE TITLE
Error in addning codes

### ISSUE THREAD

**Issue by RestOp** [lbschenkel/broadlink-bridge#9]
Hello,

i have this config 

`[commands]
# Commands are codes that can be referred to by name.
# If an incoming code matches a command name, the command code is
# sent to the device instead.
#
# For example, the code below will be sent 5 times (4 repeats):
lamp/power-on = gGEAwgKCCsIKwgJCSoICggrCAoICggrCCsICQkqCQkJCQgrCAoIKwgKCCoJCggqCAoIKwgKCCoJCggqCAoIKwgKCCsICggrCAoIKggrCAoICggrCAoIKgkJCCsIKwgKCAABXQhUCCsICggJCSoJKggKCAoIKwgrBwoICggrCAoIKwgKCCoJCQkqCAoIKwgrCAoIKggKCSoICggKCCsIKwgKCCoICgkKBysICggrCAoIKwgKCCsICggqCAoIKwgKCCsICggqCQkIKwgKCCsICggqCSoICggKCCsICggrCAoIKgkqCAoIAAFeCFMJKggKCQkIKwgrCAoICggrCCsICggKCCsICgcrCQkIKwgKCCsICggrCCsICggqCQoIKggKCQoHKwkqCAoIKwgKCAoIKwgKCCsICggrCAoIKwgJCSoJCQgrCAoIKwgKCCsICggrCAoIKwgKCCsIKgkJCQkJKwcKCCsJCQgrCCsICggAAV4IVAgqCQoICggrCCsHCgkJCSoIKwgKCAoIKwgKCCsICggrCAoIKwgKCCsIKwgKCCsICggrCAoICggrCCsICggqCQkJCgcsCAkJKgkJCCsICggrCAoIKwgKCCsICggrCAoIKwgJCSoJCgcrCAsIKggrCAoICggrCAoIKwgKCCsIKwgKCAABXQhUCSoICggKCCsIKwgKCAoIKwgrCAoICggrCAoIKwgJCSoJCggqCQkILAgqCAoIKwgKCCsICggKCCsIKwgKCCsICggKCCsICggrCAoIKwgKCCoJCggrCAkILAgKCCsICQgrCAoIKwgKCCsICggrCCsICggKCCsICggrCAoIKwgrCAoIAAFdCVQIKgkKCAkILAgqCAoJCQkrCCoJCggKCCsICggrCAoIKwgKCCsICggrCCsICggrCAoIKwgKCAoIKwgrCAoIKwgKCAoIKwgKCCsICggrCAoIKwgKCCsICggrCAoIKwgKCCsICggrCAoIKwgKCCsIKwgKCAoIKwgKCCsICggrCCsICggAAV4IVAgqCQkJCQkrCCsICQkJCSoJKwgKCAkJKgkJCSsHCwgrCAoHLAgKCCsIKgkKCCsICQkrCAoICggrCCsICggrCAoICggrCAoIKwgKCCoJCggqCQoIKwgKCCsICggrCAoIKwgJCSsICggrCAoIKwgrCAoICggrCAoIKwgKCCsIKwgKCAAF3AAAAA=

[devices]
# Known devices that will be exposed via the bridge.
# The key is the alias that the device can be addressed as.
# The value is the host (name or IP) of the Broadlink device.
myalias = 192.168.178.21

[discovery]
# The bridge can also discover nearby devices (same subnet).
#
# Number of seconds in which to wait for devices to reply during discovery.
# A value of 0 disables auto-discovery.
timeout = 5
 
[http]
# The port that the REST service will use.
# 8780 is the default port. Use 0 to disable.
port = 8780`

and get error by initialisation

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-12-17 16:24:30,119 INFO     Starting broadlink-bridge/0.1.6...
2020-12-17 16:24:30,121 INFO     Reading config file: /config/broadlink-bridge.ini
2020-12-17 16:24:30,122 INFO     Registering command: lamp/power-on
Traceback (most recent call last):
  File "/usr/local/bin/broadlink-bridge", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/cli.py", line 59, in main
    REGISTRY.set_command(command, payload)
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/__init__.py", line 66, in set_command
    self._commands[command] = ir_decode(data)[0]
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/util.py", line 63, in ir_decode
    code = base64.b64decode(code)
  File "/usr/local/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1209) cannot be 1 more than a multiple of 4
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.` 

It is the 100% working code.

**Comment by RestOp** [comment]
Sorry, better with pictures

![image](https://user-images.githubusercontent.com/46259141/102507983-27f30c80-4085-11eb-961c-67c43e9a4165.png)

![image](https://user-images.githubusercontent.com/46259141/102507711-dcd8f980-4084-11eb-8219-40150ec8cbd3.png)

**Comment by lbschenkel** [comment]
I don't think this command is right, because it is not of the right length for a BASE64 encoding. Tested with multiple tools and they all gave the same result.

**Comment by lbschenkel** [comment]
Closing due to lack of feedback.
